/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package uaspbo;

import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JTextArea;

/**
 *
 * @author M IQBAL
 */
public class AntrianForm extends javax.swing.JFrame {
        private Antrian antrian;
        
        public AntrianForm(){
            DBConnector.initDBConnection();
            initComponents();
        }
        public AntrianForm(Antrian antrian) {
            DBConnector.initDBConnection();
            initComponents();
            this.antrian = antrian;
            setDefaultCloseOperation(DISPOSE_ON_CLOSE);
            showQueueData();
        }
        
public void showQueueData() {
    System.out.println(antrian.getQueue());
    JTextArea textArea = ta_listAntrian;
    textArea.setText("");
        for (String data : antrian.getQueue()){
                textArea.append(data+"\n");
        }
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btn_panggil = new javax.swing.JToggleButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        ta_listAntrian = new javax.swing.JTextArea();
        btn_reset = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn_panggil.setBackground(new java.awt.Color(254, 254, 254));
        btn_panggil.setFont(new java.awt.Font("Segoe Print", 1, 24)); // NOI18N
        btn_panggil.setForeground(new java.awt.Color(193, 0, 45));
        btn_panggil.setText("Panggil Antrian");
        btn_panggil.setToolTipText("");
        btn_panggil.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 10, 10, 10));
        btn_panggil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_panggilActionPerformed(evt);
            }
        });
        jPanel1.add(btn_panggil, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 500, 250, 70));

        ta_listAntrian.setEditable(false);
        ta_listAntrian.setBackground(new java.awt.Color(255, 255, 255));
        ta_listAntrian.setColumns(20);
        ta_listAntrian.setFont(new java.awt.Font("Segoe Print", 1, 18)); // NOI18N
        ta_listAntrian.setForeground(new java.awt.Color(193, 0, 45));
        ta_listAntrian.setRows(5);
        ta_listAntrian.setBorder(javax.swing.BorderFactory.createEmptyBorder(50, 10, 10, 50));
        jScrollPane1.setViewportView(ta_listAntrian);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 260, 710, 600));

        btn_reset.setBackground(new java.awt.Color(253, 206, 4));
        btn_reset.setFont(new java.awt.Font("Segoe Print", 1, 14)); // NOI18N
        btn_reset.setForeground(new java.awt.Color(193, 0, 45));
        btn_reset.setText("Reset Database");
        btn_reset.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 10, 10, 10));
        btn_reset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_resetActionPerformed(evt);
            }
        });
        jPanel1.add(btn_reset, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 890, 240, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Antrian.png"))); // NOI18N
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 950));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1274, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btn_panggilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_panggilActionPerformed
        if(antrian.isEmpty()){
            JOptionPane.showMessageDialog(this,"Antrian Kosong!!!!");
        } else {
            String x = antrian.dequeue();
            String[] elemen = x.split(" - ");
            String id_transaksi = elemen[0];
            String nomor = elemen[1];
            String nama = elemen[2];
                JOptionPane.showMessageDialog(this, "Antrian yang dipanggil adalah nomor : "+nomor+" , Atas nama : "+nama+". Silakan Datang Ke Kasir"); 
        }
        showQueueData();
        
    }//GEN-LAST:event_btn_panggilActionPerformed

    private void btn_resetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_resetActionPerformed

        if(!antrian.isEmpty()){
            JOptionPane.showMessageDialog(this, "Antrian Masih Ada, Silakan selesaikan antrian terlebih dahulu");
        } else {
            try {
                Transaksi transaksi = new Transaksi();
                transaksi.resetDatabase();
                addWindowListener(new WindowAdapter(){
                    public void windowClosing(WindowEvent e){
                         System.exit(0);
                    }                   
                });
                
            } catch (SQLException ex) {
                Logger.getLogger(AntrianForm.class.getName()).log(Level.SEVERE, null, ex);
            }
        }   
        
        
    }//GEN-LAST:event_btn_resetActionPerformed
  
   
    
    
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AntrianForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AntrianForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AntrianForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AntrianForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AntrianForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton btn_panggil;
    private javax.swing.JButton btn_reset;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea ta_listAntrian;
    // End of variables declaration//GEN-END:variables
}
