/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package uaspbo;

import javax.swing.JOptionPane;

/**
 *
 * @author M IQBAL
 */
public class TambahMenuForm extends javax.swing.JFrame {
    int totalBelanja = 1;
    public TambahMenuForm() {
        initComponents();
        setDefaultCloseOperation(DISPOSE_ON_CLOSE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel11 = new javax.swing.JLabel();
        btn_bucket = new javax.swing.JToggleButton();
        label_menu1 = new javax.swing.JLabel();
        label_harga1 = new javax.swing.JLabel();
        btn_wings = new javax.swing.JToggleButton();
        label_menu2 = new javax.swing.JLabel();
        label_harga2 = new javax.swing.JLabel();
        btn_wingercombo = new javax.swing.JToggleButton();
        label_menu6 = new javax.swing.JLabel();
        label_harga6 = new javax.swing.JLabel();
        btn_pudding = new javax.swing.JToggleButton();
        label_menu3 = new javax.swing.JLabel();
        label_harga3 = new javax.swing.JLabel();
        label_harga5 = new javax.swing.JLabel();
        btn_chocolate = new javax.swing.JToggleButton();
        btn_french = new javax.swing.JToggleButton();
        btn_burger = new javax.swing.JToggleButton();
        btn_latte = new javax.swing.JToggleButton();
        btn_cola = new javax.swing.JSeparator();
        label_menu5 = new javax.swing.JLabel();
        btn_cappucino = new javax.swing.JToggleButton();
        label_harga4 = new javax.swing.JLabel();
        label_menu4 = new javax.swing.JLabel();
        label_menu7 = new javax.swing.JLabel();
        label_harga7 = new javax.swing.JLabel();
        label_menu8 = new javax.swing.JLabel();
        label_harga8 = new javax.swing.JLabel();
        label_menu9 = new javax.swing.JLabel();
        label_harga9 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        jLabel11.setText("jLabel11");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn_bucket.setForeground(new java.awt.Color(255, 255, 255));
        btn_bucket.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/bucket 9.png"))); // NOI18N
        btn_bucket.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 2, true));
        btn_bucket.setContentAreaFilled(false);
        btn_bucket.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_bucketActionPerformed(evt);
            }
        });
        getContentPane().add(btn_bucket, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 370, 120, 130));

        label_menu1.setFont(new java.awt.Font("Segoe Print", 1, 24)); // NOI18N
        label_menu1.setForeground(new java.awt.Color(255, 255, 255));
        label_menu1.setText("9 Pcs Bucket");
        getContentPane().add(label_menu1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 400, -1, -1));

        label_harga1.setFont(new java.awt.Font("Segoe Print", 1, 24)); // NOI18N
        label_harga1.setForeground(new java.awt.Color(255, 255, 255));
        label_harga1.setText("Rp 153.000");
        getContentPane().add(label_harga1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 440, -1, -1));

        btn_wings.setForeground(new java.awt.Color(255, 255, 255));
        btn_wings.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/wings bucket.png"))); // NOI18N
        btn_wings.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 2, true));
        btn_wings.setContentAreaFilled(false);
        btn_wings.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_wingsActionPerformed(evt);
            }
        });
        getContentPane().add(btn_wings, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 370, 120, 130));

        label_menu2.setFont(new java.awt.Font("Segoe Print", 1, 24)); // NOI18N
        label_menu2.setForeground(new java.awt.Color(255, 255, 255));
        label_menu2.setText("Winger Combo BBQ");
        getContentPane().add(label_menu2, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 390, -1, -1));

        label_harga2.setFont(new java.awt.Font("Segoe Print", 1, 24)); // NOI18N
        label_harga2.setForeground(new java.awt.Color(255, 255, 255));
        label_harga2.setText("Rp 67.000");
        getContentPane().add(label_harga2, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 430, -1, -1));

        btn_wingercombo.setForeground(new java.awt.Color(255, 255, 255));
        btn_wingercombo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/winger combo bbq.png"))); // NOI18N
        btn_wingercombo.setAutoscrolls(true);
        btn_wingercombo.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 2, true));
        btn_wingercombo.setContentAreaFilled(false);
        btn_wingercombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_wingercomboActionPerformed(evt);
            }
        });
        getContentPane().add(btn_wingercombo, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 360, 150, 140));

        label_menu6.setFont(new java.awt.Font("Segoe Print", 1, 24)); // NOI18N
        label_menu6.setForeground(new java.awt.Color(255, 255, 255));
        label_menu6.setText("Pudding RTE");
        getContentPane().add(label_menu6, new org.netbeans.lib.awtextra.AbsoluteConstraints(1050, 610, -1, -1));

        label_harga6.setFont(new java.awt.Font("Segoe Print", 1, 24)); // NOI18N
        label_harga6.setForeground(new java.awt.Color(255, 255, 255));
        label_harga6.setText("Rp 5.000");
        getContentPane().add(label_harga6, new org.netbeans.lib.awtextra.AbsoluteConstraints(1050, 650, -1, -1));

        btn_pudding.setForeground(new java.awt.Color(255, 255, 255));
        btn_pudding.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/pudding rte.png"))); // NOI18N
        btn_pudding.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 2, true));
        btn_pudding.setContentAreaFilled(false);
        btn_pudding.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_puddingActionPerformed(evt);
            }
        });
        getContentPane().add(btn_pudding, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 580, 120, 130));

        label_menu3.setFont(new java.awt.Font("Segoe Print", 1, 24)); // NOI18N
        label_menu3.setForeground(new java.awt.Color(255, 255, 255));
        label_menu3.setText("Wings Bucket");
        getContentPane().add(label_menu3, new org.netbeans.lib.awtextra.AbsoluteConstraints(1050, 390, -1, -1));

        label_harga3.setFont(new java.awt.Font("Segoe Print", 1, 24)); // NOI18N
        label_harga3.setForeground(new java.awt.Color(255, 255, 255));
        label_harga3.setText("Rp 83.000 ");
        getContentPane().add(label_harga3, new org.netbeans.lib.awtextra.AbsoluteConstraints(1050, 430, -1, -1));

        label_harga5.setFont(new java.awt.Font("Segoe Print", 1, 24)); // NOI18N
        label_harga5.setForeground(new java.awt.Color(255, 255, 255));
        label_harga5.setText("Rp 24.000");
        getContentPane().add(label_harga5, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 650, -1, -1));

        btn_chocolate.setForeground(new java.awt.Color(255, 255, 255));
        btn_chocolate.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/ice blend chocolate.png"))); // NOI18N
        btn_chocolate.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 2, true));
        btn_chocolate.setContentAreaFilled(false);
        btn_chocolate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_chocolateActionPerformed(evt);
            }
        });
        getContentPane().add(btn_chocolate, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 770, 150, 130));

        btn_french.setForeground(new java.awt.Color(255, 255, 255));
        btn_french.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/french fries large.png"))); // NOI18N
        btn_french.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 2, true));
        btn_french.setContentAreaFilled(false);
        btn_french.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_frenchActionPerformed(evt);
            }
        });
        getContentPane().add(btn_french, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 580, 150, 130));

        btn_burger.setForeground(new java.awt.Color(255, 255, 255));
        btn_burger.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/colonel burger.png"))); // NOI18N
        btn_burger.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 2, true));
        btn_burger.setContentAreaFilled(false);
        btn_burger.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_burgerActionPerformed(evt);
            }
        });
        getContentPane().add(btn_burger, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 580, 120, 130));

        btn_latte.setForeground(new java.awt.Color(255, 255, 255));
        btn_latte.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/ice latte.png"))); // NOI18N
        btn_latte.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 2, true));
        btn_latte.setContentAreaFilled(false);
        btn_latte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_latteActionPerformed(evt);
            }
        });
        getContentPane().add(btn_latte, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 770, 120, 130));

        btn_cola.setForeground(new java.awt.Color(0, 0, 0));
        getContentPane().add(btn_cola, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 640, 1140, 0));

        label_menu5.setFont(new java.awt.Font("Segoe Print", 1, 24)); // NOI18N
        label_menu5.setForeground(new java.awt.Color(255, 255, 255));
        label_menu5.setText("French Fries Large");
        getContentPane().add(label_menu5, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 610, 230, -1));

        btn_cappucino.setForeground(new java.awt.Color(255, 255, 255));
        btn_cappucino.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/ice blend cappuciono.png"))); // NOI18N
        btn_cappucino.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 2, true));
        btn_cappucino.setContentAreaFilled(false);
        btn_cappucino.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cappucinoActionPerformed(evt);
            }
        });
        getContentPane().add(btn_cappucino, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 770, 120, 130));

        label_harga4.setFont(new java.awt.Font("Segoe Print", 1, 24)); // NOI18N
        label_harga4.setForeground(new java.awt.Color(255, 255, 255));
        label_harga4.setText("Rp 29.000");
        getContentPane().add(label_harga4, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 650, -1, -1));

        label_menu4.setFont(new java.awt.Font("Segoe Print", 1, 24)); // NOI18N
        label_menu4.setForeground(new java.awt.Color(255, 255, 255));
        label_menu4.setText("Colonel Burger");
        getContentPane().add(label_menu4, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 610, 190, -1));

        label_menu7.setFont(new java.awt.Font("Segoe Print", 1, 24)); // NOI18N
        label_menu7.setForeground(new java.awt.Color(255, 255, 255));
        label_menu7.setText("Ice Cappucino");
        getContentPane().add(label_menu7, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 800, -1, -1));

        label_harga7.setFont(new java.awt.Font("Segoe Print", 1, 24)); // NOI18N
        label_harga7.setForeground(new java.awt.Color(255, 255, 255));
        label_harga7.setText("Rp 15.000");
        getContentPane().add(label_harga7, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 840, -1, -1));

        label_menu8.setFont(new java.awt.Font("Segoe Print", 1, 24)); // NOI18N
        label_menu8.setForeground(new java.awt.Color(255, 255, 255));
        label_menu8.setText("Ice Blend Chocolate");
        getContentPane().add(label_menu8, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 800, -1, -1));

        label_harga8.setFont(new java.awt.Font("Segoe Print", 1, 24)); // NOI18N
        label_harga8.setForeground(new java.awt.Color(255, 255, 255));
        label_harga8.setText("Rp 15.000");
        getContentPane().add(label_harga8, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 850, -1, -1));

        label_menu9.setFont(new java.awt.Font("Segoe Print", 1, 24)); // NOI18N
        label_menu9.setForeground(new java.awt.Color(255, 255, 255));
        label_menu9.setText("Iced Latte");
        getContentPane().add(label_menu9, new org.netbeans.lib.awtextra.AbsoluteConstraints(1060, 800, -1, -1));

        label_harga9.setFont(new java.awt.Font("Segoe Print", 1, 24)); // NOI18N
        label_harga9.setForeground(new java.awt.Color(255, 255, 255));
        label_harga9.setText("Rp 15.000");
        getContentPane().add(label_harga9, new org.netbeans.lib.awtextra.AbsoluteConstraints(1060, 840, -1, -1));

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Menu Tambah.png"))); // NOI18N
        jLabel1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 2, true));
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btn_bucketActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_bucketActionPerformed
        String nama =   label_menu1.getText();
        String hargaString = label_harga1.getText();
        hargaString = hargaString.replaceAll("[^\\d.]", "");
        hargaString = hargaString.replace(".","");
        float hargaFloat = Float.parseFloat(hargaString);
  
        int jumlah = Integer.parseInt(JOptionPane.showInputDialog("Masukkan Jumlah Pesanan"));
        float jumlahFloat = (float) jumlah;
        
        float total = hargaFloat*jumlahFloat;
        
        DetailMenu.AddRowToJTable(new Object[]{
            totalBelanja++,
            nama,
            hargaFloat,
            jumlah,
            total       
       });
    }//GEN-LAST:event_btn_bucketActionPerformed

    private void btn_wingercomboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_wingercomboActionPerformed
        String nama =   label_menu2.getText();
        String hargaString = label_harga2.getText();
        hargaString = hargaString.replaceAll("[^\\d.]", "");
        hargaString = hargaString.replace(".","");
        float hargaFloat = Float.parseFloat(hargaString);
  
        int jumlah = Integer.parseInt(JOptionPane.showInputDialog("Masukkan Jumlah Pesanan"));
        float jumlahFloat = (float) jumlah;
        
        float total = hargaFloat*jumlahFloat;
        
        DetailMenu.AddRowToJTable(new Object[]{
            totalBelanja++,
            nama,
            hargaFloat,
            jumlah,
            total       
       });
    }//GEN-LAST:event_btn_wingercomboActionPerformed

    private void btn_wingsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_wingsActionPerformed
        String nama =   label_menu3.getText();
        String hargaString = label_harga3.getText();
        hargaString = hargaString.replaceAll("[^\\d.]", "");
        hargaString = hargaString.replace(".","");
        float hargaFloat = Float.parseFloat(hargaString);
  
        int jumlah = Integer.parseInt(JOptionPane.showInputDialog("Masukkan Jumlah Pesanan"));
        float jumlahFloat = (float) jumlah;
        
        float total = hargaFloat*jumlahFloat;
        
        DetailMenu.AddRowToJTable(new Object[]{
            totalBelanja++,
            nama,
            hargaFloat,
            jumlah,
            total       
       });
    }//GEN-LAST:event_btn_wingsActionPerformed

    private void btn_burgerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_burgerActionPerformed
        String nama =   label_menu4.getText();
        String hargaString = label_harga4.getText();
        hargaString = hargaString.replaceAll("[^\\d.]", "");
        hargaString = hargaString.replace(".","");
        float hargaFloat = Float.parseFloat(hargaString);
  
        int jumlah = Integer.parseInt(JOptionPane.showInputDialog("Masukkan Jumlah Pesanan"));
        float jumlahFloat = (float) jumlah;
        
        float total = hargaFloat*jumlahFloat;
        
        DetailMenu.AddRowToJTable(new Object[]{
            totalBelanja++,
            nama,
            hargaFloat,
            jumlah,
            total       
       });
    }//GEN-LAST:event_btn_burgerActionPerformed

    private void btn_frenchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_frenchActionPerformed
         String nama =   label_menu5.getText();
        String hargaString = label_harga5.getText();
        hargaString = hargaString.replaceAll("[^\\d.]", "");
        hargaString = hargaString.replace(".","");
        float hargaFloat = Float.parseFloat(hargaString);
  
        int jumlah = Integer.parseInt(JOptionPane.showInputDialog("Masukkan Jumlah Pesanan"));
        float jumlahFloat = (float) jumlah;
        
        float total = hargaFloat*jumlahFloat;
        
        DetailMenu.AddRowToJTable(new Object[]{
            totalBelanja++,
            nama,
            hargaFloat,
            jumlah,
            total       
       });
    }//GEN-LAST:event_btn_frenchActionPerformed

    private void btn_puddingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_puddingActionPerformed
        String nama =   label_menu6.getText();
        String hargaString = label_harga6.getText();
        hargaString = hargaString.replaceAll("[^\\d.]", "");
        hargaString = hargaString.replace(".","");
        float hargaFloat = Float.parseFloat(hargaString);
  
        int jumlah = Integer.parseInt(JOptionPane.showInputDialog("Masukkan Jumlah Pesanan"));
        float jumlahFloat = (float) jumlah;
        
        float total = hargaFloat*jumlahFloat;
        
        DetailMenu.AddRowToJTable(new Object[]{
            totalBelanja++,
            nama,
            hargaFloat,
            jumlah,
            total       
       });
    }//GEN-LAST:event_btn_puddingActionPerformed

    private void btn_cappucinoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cappucinoActionPerformed
        String nama =   label_menu7.getText();
        String hargaString = label_harga7.getText();
        hargaString = hargaString.replaceAll("[^\\d.]", "");
        hargaString = hargaString.replace(".","");
        float hargaFloat = Float.parseFloat(hargaString);
  
        int jumlah = Integer.parseInt(JOptionPane.showInputDialog("Masukkan Jumlah Pesanan"));
        float jumlahFloat = (float) jumlah;
        
        float total = hargaFloat*jumlahFloat;
        
        DetailMenu.AddRowToJTable(new Object[]{
            totalBelanja++,
            nama,
            hargaFloat,
            jumlah,
            total       
       });
    }//GEN-LAST:event_btn_cappucinoActionPerformed

    private void btn_chocolateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_chocolateActionPerformed
        String nama =   label_menu8.getText();
        String hargaString = label_harga8.getText();
        hargaString = hargaString.replaceAll("[^\\d.]", "");
        hargaString = hargaString.replace(".","");
        float hargaFloat = Float.parseFloat(hargaString);
  
        int jumlah = Integer.parseInt(JOptionPane.showInputDialog("Masukkan Jumlah Pesanan"));
        float jumlahFloat = (float) jumlah;
        
        float total = hargaFloat*jumlahFloat;
        
        DetailMenu.AddRowToJTable(new Object[]{
            totalBelanja++,
            nama,
            hargaFloat,
            jumlah,
            total       
       });
    }//GEN-LAST:event_btn_chocolateActionPerformed

    private void btn_latteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_latteActionPerformed
        String nama =   label_menu9.getText();
        String hargaString = label_harga9.getText();
        hargaString = hargaString.replaceAll("[^\\d.]", "");
        hargaString = hargaString.replace(".","");
        float hargaFloat = Float.parseFloat(hargaString);
  
        int jumlah = Integer.parseInt(JOptionPane.showInputDialog("Masukkan Jumlah Pesanan"));
        float jumlahFloat = (float) jumlah;
        
        float total = hargaFloat*jumlahFloat;
        
        DetailMenu.AddRowToJTable(new Object[]{
            totalBelanja++,
            nama,
            hargaFloat,
            jumlah,
            total       
       });
    }//GEN-LAST:event_btn_latteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TambahMenuForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TambahMenuForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TambahMenuForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TambahMenuForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TambahMenuForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton btn_bucket;
    private javax.swing.JToggleButton btn_burger;
    private javax.swing.JToggleButton btn_cappucino;
    private javax.swing.JToggleButton btn_chocolate;
    private javax.swing.JSeparator btn_cola;
    private javax.swing.JToggleButton btn_french;
    private javax.swing.JToggleButton btn_latte;
    private javax.swing.JToggleButton btn_pudding;
    private javax.swing.JToggleButton btn_wingercombo;
    private javax.swing.JToggleButton btn_wings;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel label_harga1;
    private javax.swing.JLabel label_harga2;
    private javax.swing.JLabel label_harga3;
    private javax.swing.JLabel label_harga4;
    private javax.swing.JLabel label_harga5;
    private javax.swing.JLabel label_harga6;
    private javax.swing.JLabel label_harga7;
    private javax.swing.JLabel label_harga8;
    private javax.swing.JLabel label_harga9;
    private javax.swing.JLabel label_menu1;
    private javax.swing.JLabel label_menu2;
    private javax.swing.JLabel label_menu3;
    private javax.swing.JLabel label_menu4;
    private javax.swing.JLabel label_menu5;
    private javax.swing.JLabel label_menu6;
    private javax.swing.JLabel label_menu7;
    private javax.swing.JLabel label_menu8;
    private javax.swing.JLabel label_menu9;
    // End of variables declaration//GEN-END:variables
}
